name: guinness
version: 0.1.16
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/guinness
description: A port of the Jasmine testing framework.
dependencies:
  collection: ">=0.9.1 <2.0.0"
  test: ">= 0.12.0-beta.7 <0.13.0"
dev_dependencies:
  browser: ">= 0.10.0 <1.0.0"
environment:
  sdk: ">=1.3.0 <2.0.0"
